### ISSUE TITLE
本mod与自定义游戏加载界面mod冲突

### ISSUE THREAD

**Issue by jianaiyuxin** [GaylordFockerCN/WuKong#2]
[错误报告-2024-10-9_14.42.48.zip](https://github.com/user-attachments/files/17303419/-2024-10-9_14.42.48.zip)

**Comment by P1neapplell0** [comment]
堆栈没有Wukong相关，可以确定一下是否是史诗战斗不兼容，并尝试看看奇迹武器是否兼容

**Comment by jianaiyuxin** [comment]
此问题已解决，最新版本自定义游戏加载界面修复了崩溃问题
